#pragma once

#define APP_LINE_FOLLOW 0
#define APP_H_QUESTION 1

#ifndef APP_ACTIVE
#define APP_ACTIVE APP_H_QUESTION
#endif

#if APP_ACTIVE != APP_LINE_FOLLOW && APP_ACTIVE != APP_H_QUESTION
#error "APP_ACTIVE must be APP_LINE_FOLLOW or APP_H_QUESTION"
#endif
