#ifndef TI_CAR_BASE_ATTITUDE_BACKEND_CONFIG_H_
#define TI_CAR_BASE_ATTITUDE_BACKEND_CONFIG_H_

/* Select exactly one backend. DMP is the default production target. */
#define ATTITUDE_BACKEND_DMP 1
#define ATTITUDE_BACKEND_COMPLEMENTARY 2
#define ATTITUDE_BACKEND_KALMAN 3

#ifndef ATTITUDE_CONFIG_BACKEND
#define ATTITUDE_CONFIG_BACKEND ATTITUDE_BACKEND_DMP
#endif

#if ATTITUDE_CONFIG_BACKEND == ATTITUDE_BACKEND_DMP
#define ATTITUDE_FILTER_IMPL_DMP
#elif ATTITUDE_CONFIG_BACKEND == ATTITUDE_BACKEND_COMPLEMENTARY
#define ATTITUDE_FILTER_IMPL_COMPLEMENTARY
#elif ATTITUDE_CONFIG_BACKEND == ATTITUDE_BACKEND_KALMAN
#define ATTITUDE_FILTER_IMPL_KALMAN
#else
#error "ATTITUDE_CONFIG_BACKEND must select DMP, COMPLEMENTARY, or KALMAN"
#endif

#define EMPL_TARGET_MSPM0
#define EMPL_SENSOR_MPU6050

#endif
