#ifndef ATTITUDE_BACKEND_CONFIG_H
#define ATTITUDE_BACKEND_CONFIG_H

#define ATTITUDE_BACKEND_DMP 0
#define ATTITUDE_BACKEND_COMPLEMENTARY 1
#define ATTITUDE_BACKEND_KALMAN 2
#define ATTITUDE_BACKEND_MAHONY 3

#ifndef ATTITUDE_CONFIG_BACKEND
#define ATTITUDE_CONFIG_BACKEND ATTITUDE_BACKEND_COMPLEMENTARY
#endif

#if ATTITUDE_CONFIG_BACKEND != ATTITUDE_BACKEND_DMP &&                         \
    ATTITUDE_CONFIG_BACKEND != ATTITUDE_BACKEND_COMPLEMENTARY &&               \
    ATTITUDE_CONFIG_BACKEND != ATTITUDE_BACKEND_KALMAN &&                      \
    ATTITUDE_CONFIG_BACKEND != ATTITUDE_BACKEND_MAHONY
#error "Unsupported ATTITUDE_CONFIG_BACKEND"
#endif

#if ATTITUDE_CONFIG_BACKEND == ATTITUDE_BACKEND_DMP
#define ATTITUDE_FILTER_IMPL_DMP
#define EMPL_TARGET_MSPM0
#define EMPL_SENSOR_MPU6050
#endif

#endif
