#pragma once

// Single tuning entry point for vehicle commissioning. Every value below may
// be overridden with a compiler -D option. Defaults are the imported branch
// baseline only; verify each item on the target car before race use.

#ifndef VEHICLE_TUNING_WHEEL_DIAMETER_METERS
#define VEHICLE_TUNING_WHEEL_DIAMETER_METERS 0.048F
#endif
#ifndef VEHICLE_TUNING_GEAR_RATIO
#define VEHICLE_TUNING_GEAR_RATIO 28.0F
#endif
#ifndef VEHICLE_TUNING_ENCODER_COUNTS_PER_MOTOR_REVOLUTION
#define VEHICLE_TUNING_ENCODER_COUNTS_PER_MOTOR_REVOLUTION 13.0F
#endif
#ifndef VEHICLE_TUNING_ENCODER_QUADRATURE_MULTIPLIER
#define VEHICLE_TUNING_ENCODER_QUADRATURE_MULTIPLIER 4.0F
#endif
#ifndef VEHICLE_TUNING_ENCODER_LEFT_DIRECTION
#define VEHICLE_TUNING_ENCODER_LEFT_DIRECTION 1
#endif
#ifndef VEHICLE_TUNING_ENCODER_RIGHT_DIRECTION
#define VEHICLE_TUNING_ENCODER_RIGHT_DIRECTION -1
#endif
#ifndef VEHICLE_TUNING_LINE_SENSOR_LINE_IS_HIGH
#define VEHICLE_TUNING_LINE_SENSOR_LINE_IS_HIGH 0
#endif
#ifndef VEHICLE_TUNING_LINE_HOLD_MS
#define VEHICLE_TUNING_LINE_HOLD_MS 150U
#endif
#ifndef VEHICLE_TUNING_LINE_SEARCH_TIMEOUT_MS
#define VEHICLE_TUNING_LINE_SEARCH_TIMEOUT_MS 600U
#endif
#ifndef VEHICLE_TUNING_LINE_HOLD_SPEED_RATIO
#define VEHICLE_TUNING_LINE_HOLD_SPEED_RATIO 0.50F
#endif
#ifndef VEHICLE_TUNING_LINE_SEARCH_SPEED_RATIO
#define VEHICLE_TUNING_LINE_SEARCH_SPEED_RATIO 0.35F
#endif
#ifndef VEHICLE_TUNING_LED_BLINK_HALF_PERIOD_MS
#define VEHICLE_TUNING_LED_BLINK_HALF_PERIOD_MS 250U
#endif
#ifndef VEHICLE_TUNING_STARTUP_TONE_MS
#define VEHICLE_TUNING_STARTUP_TONE_MS 30U
#endif
#ifndef VEHICLE_TUNING_USER_LED_PERIOD_MS
#define VEHICLE_TUNING_USER_LED_PERIOD_MS 1000U
#endif
#ifndef VEHICLE_TUNING_USER_LED_PULSE_MS
#define VEHICLE_TUNING_USER_LED_PULSE_MS 50U
#endif

#ifndef LINE_FOLLOW_KP
#define LINE_FOLLOW_KP 45.0F
#endif
#ifndef LINE_FOLLOW_KI
#define LINE_FOLLOW_KI 0.0F
#endif
#ifndef LINE_FOLLOW_KD
#define LINE_FOLLOW_KD 0.0F
#endif
#ifndef LINE_FOLLOW_CRUISE
#define LINE_FOLLOW_CRUISE 180
#endif
#ifndef LINE_FOLLOW_CRUISE_STEP
#define LINE_FOLLOW_CRUISE_STEP 10
#endif
#ifndef LINE_FOLLOW_MAX_CRUISE
#define LINE_FOLLOW_MAX_CRUISE 500
#endif
#ifndef LINE_FOLLOW_TRACK_WIDTH_METERS
#define LINE_FOLLOW_TRACK_WIDTH_METERS 0.15F
#endif
#ifndef LINE_FOLLOW_CONTROL_PERIOD_MS
#define LINE_FOLLOW_CONTROL_PERIOD_MS 5U
#endif
#ifndef LINE_FOLLOW_ENABLE_HOLD_MS
#define LINE_FOLLOW_ENABLE_HOLD_MS 500U
#endif
#ifndef LINE_FOLLOW_TELEMETRY_PERIOD_MS
#define LINE_FOLLOW_TELEMETRY_PERIOD_MS 50U
#endif
#ifndef LINE_FOLLOW_HEARTBEAT_PERIOD_MS
#define LINE_FOLLOW_HEARTBEAT_PERIOD_MS 500U
#endif
#ifndef LINE_FOLLOW_OLED_TEXT_PERIOD_MS
#define LINE_FOLLOW_OLED_TEXT_PERIOD_MS 100U
#endif
#ifndef LINE_FOLLOW_OLED_SERVICE_PERIOD_MS
#define LINE_FOLLOW_OLED_SERVICE_PERIOD_MS 2U
#endif

#ifndef H_QUESTION_P1_DISTANCE_CM
#define H_QUESTION_P1_DISTANCE_CM 100.0F
#endif
#ifndef H_QUESTION_P2_DISTANCE_CM
#define H_QUESTION_P2_DISTANCE_CM 500.0F
#endif
#ifndef H_QUESTION_ARC_DISTANCE_CM
#define H_QUESTION_ARC_DISTANCE_CM 125.6F
#endif
#ifndef H_QUESTION_DIAGONAL_DISTANCE_CM
#define H_QUESTION_DIAGONAL_DISTANCE_CM 128.0F
#endif
#ifndef H_QUESTION_HEADING_A_TO_C_DEG
#define H_QUESTION_HEADING_A_TO_C_DEG -38.7F
#endif
#ifndef H_QUESTION_HEADING_B_TO_D_DEG
#define H_QUESTION_HEADING_B_TO_D_DEG -38.7F
#endif
#ifndef H_QUESTION_ENDPOINT_ARM_RATIO
#define H_QUESTION_ENDPOINT_ARM_RATIO 0.80F
#endif
#ifndef H_QUESTION_MINIMUM_LINE_SENSORS
#define H_QUESTION_MINIMUM_LINE_SENSORS 2U
#endif
#ifndef H_QUESTION_ENDPOINT_CONFIRM_MS
#define H_QUESTION_ENDPOINT_CONFIRM_MS 40U
#endif
#ifndef H_QUESTION_COUNTDOWN_MS
#define H_QUESTION_COUNTDOWN_MS 3000U
#endif
#ifndef H_QUESTION_CHECKPOINT_PAUSE_MS
#define H_QUESTION_CHECKPOINT_PAUSE_MS 200U
#endif

#ifndef H_QUESTION_ARC_SPEED_MM_PER_SECOND
#define H_QUESTION_ARC_SPEED_MM_PER_SECOND 100
#endif
#ifndef H_QUESTION_STRAIGHT_SPEED_MM_PER_SECOND
#define H_QUESTION_STRAIGHT_SPEED_MM_PER_SECOND 200
#endif
#ifndef H_QUESTION_MINIMUM_WHEEL_SPEED_MM_PER_SECOND
#define H_QUESTION_MINIMUM_WHEEL_SPEED_MM_PER_SECOND 80
#endif
#ifndef H_QUESTION_TRACK_WIDTH_METERS
#define H_QUESTION_TRACK_WIDTH_METERS 0.15F
#endif
#ifndef H_QUESTION_LINE_KP
#define H_QUESTION_LINE_KP 30.0F
#endif
#ifndef H_QUESTION_LINE_KI
#define H_QUESTION_LINE_KI 2.0F
#endif
#ifndef H_QUESTION_LINE_KD
#define H_QUESTION_LINE_KD 15.0F
#endif
#ifndef H_QUESTION_HEADING_KP
#define H_QUESTION_HEADING_KP 10.0F
#endif
#ifndef H_QUESTION_HEADING_KI
#define H_QUESTION_HEADING_KI 1.0F
#endif
#ifndef H_QUESTION_HEADING_KD
#define H_QUESTION_HEADING_KD 3.0F
#endif
#ifndef H_QUESTION_HEADING_INTEGRAL_LIMIT
#define H_QUESTION_HEADING_INTEGRAL_LIMIT 50.0F
#endif
#ifndef H_QUESTION_SPEED_KP
#define H_QUESTION_SPEED_KP 2.0F
#endif
#ifndef H_QUESTION_SPEED_KI
#define H_QUESTION_SPEED_KI 1.0F
#endif
#ifndef H_QUESTION_SPEED_KD
#define H_QUESTION_SPEED_KD 0.0F
#endif
#ifndef H_QUESTION_SPEED_PWM_LIMIT
#define H_QUESTION_SPEED_PWM_LIMIT 250.0F
#endif
#ifndef H_QUESTION_SPEED_INTEGRAL_LIMIT
#define H_QUESTION_SPEED_INTEGRAL_LIMIT 20.0F
#endif
#ifndef H_QUESTION_SPEED_PWM_RISE_PER_UPDATE
#define H_QUESTION_SPEED_PWM_RISE_PER_UPDATE 20
#endif

#ifndef H_QUESTION_CONTROL_PERIOD_MS
#define H_QUESTION_CONTROL_PERIOD_MS 5U
#endif
#ifndef H_QUESTION_OUTER_CONTROL_PERIOD_MS
#define H_QUESTION_OUTER_CONTROL_PERIOD_MS 100U
#endif
#ifndef H_QUESTION_SPEED_SAMPLE_PERIOD_MS
#define H_QUESTION_SPEED_SAMPLE_PERIOD_MS 50U
#endif
#ifndef H_QUESTION_CONTROL_LOG_PERIOD_MS
#define H_QUESTION_CONTROL_LOG_PERIOD_MS 50U
#endif
#ifndef H_QUESTION_OLED_TEXT_PERIOD_MS
#define H_QUESTION_OLED_TEXT_PERIOD_MS 100U
#endif
#ifndef H_QUESTION_OLED_SERVICE_PERIOD_MS
#define H_QUESTION_OLED_SERVICE_PERIOD_MS 2U
#endif
#ifndef H_QUESTION_AUTO_START_PROGRAM
#define H_QUESTION_AUTO_START_PROGRAM 0
#endif

#if VEHICLE_TUNING_ENCODER_LEFT_DIRECTION != 1 &&                              \
    VEHICLE_TUNING_ENCODER_LEFT_DIRECTION != -1
#error "VEHICLE_TUNING_ENCODER_LEFT_DIRECTION must be 1 or -1"
#endif
#if VEHICLE_TUNING_ENCODER_RIGHT_DIRECTION != 1 &&                             \
    VEHICLE_TUNING_ENCODER_RIGHT_DIRECTION != -1
#error "VEHICLE_TUNING_ENCODER_RIGHT_DIRECTION must be 1 or -1"
#endif
#if VEHICLE_TUNING_LINE_SENSOR_LINE_IS_HIGH != 0 &&                            \
    VEHICLE_TUNING_LINE_SENSOR_LINE_IS_HIGH != 1
#error "VEHICLE_TUNING_LINE_SENSOR_LINE_IS_HIGH must be 0 or 1"
#endif
#if VEHICLE_TUNING_LINE_HOLD_MS == 0
#error "VEHICLE_TUNING_LINE_HOLD_MS must be greater than zero"
#endif
#if VEHICLE_TUNING_LINE_SEARCH_TIMEOUT_MS <= VEHICLE_TUNING_LINE_HOLD_MS
#error "VEHICLE_TUNING_LINE_SEARCH_TIMEOUT_MS must exceed hold time"
#endif
#if VEHICLE_TUNING_LED_BLINK_HALF_PERIOD_MS == 0
#error "VEHICLE_TUNING_LED_BLINK_HALF_PERIOD_MS must be greater than zero"
#endif
#if VEHICLE_TUNING_STARTUP_TONE_MS == 0
#error "VEHICLE_TUNING_STARTUP_TONE_MS must be greater than zero"
#endif
#if VEHICLE_TUNING_USER_LED_PULSE_MS > VEHICLE_TUNING_USER_LED_PERIOD_MS
#error "VEHICLE_TUNING_USER_LED_PULSE_MS must not exceed its period"
#endif
#if LINE_FOLLOW_MAX_CRUISE <= 0 || LINE_FOLLOW_MAX_CRUISE > 500
#error "LINE_FOLLOW_MAX_CRUISE must be in the range 1..500"
#endif
#if LINE_FOLLOW_CRUISE < 0 || LINE_FOLLOW_CRUISE > LINE_FOLLOW_MAX_CRUISE
#error "LINE_FOLLOW_CRUISE must not exceed LINE_FOLLOW_MAX_CRUISE"
#endif
#if LINE_FOLLOW_CRUISE_STEP <= 0 ||                                            \
    LINE_FOLLOW_CRUISE_STEP > LINE_FOLLOW_MAX_CRUISE
#error "LINE_FOLLOW_CRUISE_STEP must not exceed LINE_FOLLOW_MAX_CRUISE"
#endif
#if LINE_FOLLOW_CONTROL_PERIOD_MS == 0 || LINE_FOLLOW_ENABLE_HOLD_MS == 0 ||   \
    LINE_FOLLOW_TELEMETRY_PERIOD_MS == 0 ||                                    \
    LINE_FOLLOW_HEARTBEAT_PERIOD_MS == 0 ||                                    \
    LINE_FOLLOW_OLED_TEXT_PERIOD_MS == 0 ||                                    \
    LINE_FOLLOW_OLED_SERVICE_PERIOD_MS == 0
#error "LINE_FOLLOW timing macros must be greater than zero"
#endif
#if H_QUESTION_ENDPOINT_CONFIRM_MS == 0
#error "H_QUESTION_ENDPOINT_CONFIRM_MS must be greater than zero"
#endif
#if H_QUESTION_OLED_TEXT_PERIOD_MS == 0 ||                                     \
    H_QUESTION_OLED_SERVICE_PERIOD_MS == 0
#error "H_QUESTION OLED periods must be greater than zero"
#endif
#if H_QUESTION_AUTO_START_PROGRAM < 0 || H_QUESTION_AUTO_START_PROGRAM > 4
#error "H_QUESTION_AUTO_START_PROGRAM must be in the range 0..4"
#endif

static_assert(VEHICLE_TUNING_LINE_HOLD_SPEED_RATIO >= 0.0F &&
                  VEHICLE_TUNING_LINE_HOLD_SPEED_RATIO <= 1.0F,
              "VEHICLE_TUNING_LINE_HOLD_SPEED_RATIO must be in [0, 1]");
static_assert(VEHICLE_TUNING_LINE_SEARCH_SPEED_RATIO >= 0.0F &&
                  VEHICLE_TUNING_LINE_SEARCH_SPEED_RATIO <= 1.0F,
              "VEHICLE_TUNING_LINE_SEARCH_SPEED_RATIO must be in [0, 1]");
static_assert(LINE_FOLLOW_KP >= 0.0F && LINE_FOLLOW_KP <= 300.0F,
              "LINE_FOLLOW_KP must be in [0, 300]");
static_assert(LINE_FOLLOW_KI >= 0.0F && LINE_FOLLOW_KI <= 30.0F,
              "LINE_FOLLOW_KI must be in [0, 30]");
static_assert(LINE_FOLLOW_KD >= 0.0F && LINE_FOLLOW_KD <= 100.0F,
              "LINE_FOLLOW_KD must be in [0, 100]");
static_assert(LINE_FOLLOW_TRACK_WIDTH_METERS > 0.0F,
              "LINE_FOLLOW_TRACK_WIDTH_METERS must be positive");
